server:
  port: 8080
  servlet:
    context-path: /springboot-1
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz@WSX
    url : jdbc:mysql://localhost:3306/practice?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  sql:
    init:
      platform: org.hibernate.dialect.MySQLDialect
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    # create, create-drop, update, [none]
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    excluded-view-names:
    - "*.jsp"
    - "*.html"
  mvc:
    static-path-pattern: /static/**      